#define GETTEXT_PACKAGE "vte-mod"

#define ENABLE_NLS 1
#define GDK_MULTIHEAD_SAFE 1
#define GWINSZ_IN_SYS_IOCTL 1

#define HAVE_ALLOCA_H 1
#define HAVE_BIND_TEXTDOMAIN_CODESET 1
#define HAVE_CEIL 1
#define HAVE_CFMAKERAW 1
#define HAVE_CURSES_H 1
#define HAVE_DCGETTEXT 1
#define HAVE_DECL_BIND_TEXTDOMAIN_CODESET 1
#define HAVE_DLFCN_H 1
#define HAVE_ENDUTENT 1
#define HAVE_FCNTL 1
#define HAVE_FLOCK 1
#define HAVE_FORK 1
#define HAVE_FORKPTY 1
#define HAVE_GETPGID 1
#define HAVE_GETPT 1
#define HAVE_GETTEXT 1
#define HAVE_GETTTYENT 1
#define HAVE_GETUTENT 1
#define HAVE_GETUTMPX 1
#define HAVE_GRANTPT 1
#define HAVE_INTTYPES_H 1
#define HAVE_LASTLOG_H 1
#define HAVE_LC_MESSAGES 1
#define HAVE_LIBUTIL 1
#define HAVE_LOCALE_H 1
#define HAVE_LOGIN_TTY 1
#define HAVE_MEMORY_H 1
#define HAVE_NCURSES_H 1
#define HAVE_OPENPTY 1
#define HAVE_PATHS_H 1
#define HAVE_PTSNAME 1
#define HAVE_PTSNAME_R 1
#define HAVE_PTY_H 1
#define HAVE_RECVMSG 1
#define HAVE_REVOKE 1
#define HAVE_SENDMSG 1
#define HAVE_SETEUID 1
#define HAVE_SETPGID 1
#define HAVE_SETREUID 1
#define HAVE_SETSID 1
#define HAVE_SETUTENT 1
#define HAVE_SOCKET 1
#define HAVE_SOCKETPAIR 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_STROPTS_H 1
#define HAVE_STRRCHR 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TERMIOS_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_UN_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_TCGETATTR 1
#define HAVE_TCSETATTR 1
#define HAVE_TERMCAP_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_TERM_H 1
#define HAVE_TTYENT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_UNLOCKPT 1
#define HAVE_UPDWTMP 1
#define HAVE_UPDWTMPX 1
#define HAVE_UTMPNAME 1
#define HAVE_UTMPXNAME 1
#define HAVE_UTMPX_H 1
#define HAVE_UTMP_H 1
#define HAVE_UT_UT_EXIT_E_TERMINATION 1
#define HAVE_UT_UT_HOST 1
#define HAVE_UT_UT_ID 1
#define HAVE_UT_UT_NAME 1
#define HAVE_UT_UT_PID 1
#define HAVE_UT_UT_TIME 1
#define HAVE_UT_UT_TV 1
#define HAVE_UT_UT_TYPE 1
#define HAVE_UT_UT_USER 1
#define HAVE_WCHAR_H 1
#define HAVE_WINT_T /**/

#define LT_OBJDIR ".libs/"
#define PACKAGE "vte"
#define PACKAGE_BUGREPORT "http://bugzilla.gnome.org/enter_bug.cgi?product=vte"
#define PACKAGE_NAME "vte"
#define PACKAGE_STRING "vte 0.28.2"
#define PACKAGE_TARNAME "vte"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "0.28.2"
#define STDC_HEADERS 1
#define TIME_WITH_SYS_TIME 1
#define UTMP struct utmpx
#define VERSION "0.28.2"
#define VTE_DEFAULT_EMULATION "xterm"
//#define VTE_USE_GNOME_PTY_HELPER 1
#define _GNU_SOURCE 1

#define LOCALEDIR "/usr/share/locale"
#define TERMCAPDIR "/etc/termcaps"
#define LIBEXECDIR "/lib"
